<?php
/**
 * @author : Martti Syber
 */

 // Funnycoon Menu Class
require get_template_directory() . '/classes/Funnycoon_Menu.php';

/**
 * 
 * Add theme scripts and styles
 * 
 */

function funnycoon_scripts() {
    wp_enqueue_style('funnycoon-styles', get_template_directory_uri() . '/assets/css/styles.css');
    wp_enqueue_script('funnycoon-scripts', get_template_directory_uri() . '/assets/js/funnycoon_scripts.js', [], false, true);
};
add_action('wp_enqueue_scripts', 'funnycoon_scripts');

/**
 * Custom favicon for site. Favicons was generated by Favvy Favicon Exporter in Figma
 */

add_action( 'wp_head', 'add_favicon' );
add_action( 'admin_head', 'add_favicon' );

function add_favicon() {
    printf(
      '<link rel="icon" type="image/svg+xml" href="' . get_template_directory_uri() . '/assets/favicon/favicon.svg">'
    );
}

/**
 * 
 * Theme Setup
 * 
 */

function funnycoon_setup() {
    register_nav_menus( array(
        'header_menu' => "Меню в header'e",
    ) );
}
add_action('after_setup_theme', 'funnycoon_setup');

/**
 * 
 * Thumbnail custom setting (delete all sizes except thumbnail)
 * 
 */

function devise_remove_default_image_sizes( $sizes) {
    unset( $sizes['thumbnail']);
    unset( $sizes['medium']);
    unset( $sizes['medium_large']);
    unset( $sizes['large']);
    unset( $sizes['768x432'] );
    unset( $sizes['1536x1536']); // disable 2x medium-large size
	unset( $sizes['2048x2048']); // disable 2x large size
    
    return $sizes;
}
add_filter('intermediate_image_sizes_advanced', 'devise_remove_default_image_sizes');