<?php 

/**
  * 
  * Add theme scripts and styles
  * 
  */
 
  function funnycoon_scripts() {
    wp_deregister_script( 'jquery' );
    wp_register_script( 'jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js');
    wp_enqueue_script( 'jquery' );
    wp_enqueue_style('funnycoon-styles', get_template_directory_uri() . '/assets/css/styles.css');
    wp_enqueue_script('funnycoon-scripts', get_template_directory_uri() . '/assets/js/funnycoon_scripts.js', [], false, true);
    wp_enqueue_script('funnycoon-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_loadmore.js', [], false, true);
    wp_enqueue_script('funnycoon-review-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_review_loadmore.js', [], false, true);
    wp_enqueue_script('funnycoon-tops-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_tops_loadmore.js', [], false, true);

    wp_localize_script('funnycoon-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('loadmore_post_nonce'),
    ) );

    wp_localize_script('funnycoon-review-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('review_loadmore_post_nonce'),
    ) );

    wp_localize_script('funnycoon-tops-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('tops_loadmore_post_nonce'),
    ) );

};

add_action('wp_enqueue_scripts', 'funnycoon_scripts');

 // Funnycoon Menu Class
 require get_template_directory() . '/classes/Funnycoon_Menu.php';

 /**
  * Implement load more functions
  */

require trailingslashit( get_template_directory() ) . 'inc/funnycoon-loadmore.php';

/**
 * Implement Handlers
 */
require trailingslashit( get_template_directory() ) . 'inc/funnycoon-handlers.php';

 /**
  * Implement login & Register form
  */
  require trailingslashit( get_template_directory() ) . 'inc/funnycoon-ajax-auth.php';
 
 /**
  * Custom favicon for site. Favicons was generated by Favvy Favicon Exporter in Figma
  */
 
 add_action( 'wp_head', 'add_favicon' );
 add_action( 'admin_head', 'add_favicon' );
 
 function add_favicon() {
     printf(
       '<link rel="icon" type="image/svg+xml" href="' . get_template_directory_uri() . '/assets/favicon/favicon.svg">'
     );
 }
 
 /**
  * 
  * Theme Setup
  * 
  */
 
 function funnycoon_setup() {
     add_theme_support('title-tag');
     add_theme_support( 'post-thumbnails' );
     register_nav_menus( array(
         'header_menu' => "Меню в header'e",
     ) );
 }
 add_action('after_setup_theme', 'funnycoon_setup');
 
 /**
  * 
  * Thumbnail custom setting (delete all sizes except thumbnail)
  * 
  */
 
 function devise_remove_default_image_sizes( $sizes) {
     unset( $sizes['thumbnail']);
     unset( $sizes['medium']);
     unset( $sizes['medium_large']);
     unset( $sizes['large']);
     unset( $sizes['768x432'] );
     unset( $sizes['1536x1536']); // disable 2x medium-large size
     unset( $sizes['2048x2048']); // disable 2x large size
     
     return $sizes;
 }
 add_filter('intermediate_image_sizes_advanced', 'devise_remove_default_image_sizes');
