<?php 

/**
  * 
  * Add theme scripts and styles
  * 
  */
 
  function funnycoon_scripts() {
    wp_deregister_script( 'jquery' );
    wp_register_script( 'jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js');
    wp_enqueue_script( 'jquery' );
    wp_enqueue_style('funnycoon-styles', get_template_directory_uri() . '/assets/css/styles.css', false, time());
    wp_enqueue_style('funnycoon-fontawesome', get_template_directory_uri() . '/assets/fontawesome/css/all.min.css');
    wp_enqueue_script('funnycoon-scripts', get_template_directory_uri() . '/assets/js/funnycoon_scripts.js', [], false, true);
    wp_enqueue_script('funnycoon-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_loadmore.js', [], false, true);
    wp_enqueue_script('funnycoon-review-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_review_loadmore.js', [], false, true);
    wp_enqueue_script('funnycoon-tops-loadmore-script', get_template_directory_uri() . '/assets/js/funnycoon_tops_loadmore.js', [], false, true);

    wp_localize_script('funnycoon-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('loadmore_post_nonce'),
    ) );

    wp_localize_script('funnycoon-review-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('review_loadmore_post_nonce'),
    ) );

    wp_localize_script('funnycoon-tops-loadmore-script', 'siteConfig', array(
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'ajax_nonce' => wp_create_nonce('tops_loadmore_post_nonce'),
    ) );

    // Magnific image popup

    wp_enqueue_script('magnific-js', get_stylesheet_directory_uri() . '/assets/js/magnific_popup/jquery.magnific-popup.js', array("jquery"), false );
    wp_enqueue_script('magnific-js-2', get_stylesheet_directory_uri() . '/assets/js/magnific_popup/jquery.magnific-popup.min.js', array("jquery"), false );
 

};

add_action('wp_enqueue_scripts', 'funnycoon_scripts');

/**
 * Switch to HTML5
 */
add_theme_support(
    'html5',
    array(
        'comment-list',
        'comment-form',
    )
);

// Funnycoon Menu Class
require get_template_directory() . '/classes/funnycoon-menu.php';

// Funnycoon Comments Class
require get_template_directory() . '/classes/funnycoon-comments.php';

/**
 * Implement load more functions
 */

require trailingslashit( get_template_directory() ) . 'inc/funnycoon-loadmore.php';

/**
 * Implement Handlers
 */
require trailingslashit( get_template_directory() ) . 'inc/funnycoon-handlers.php';

/**
 * Implement login & Register form
 */
require trailingslashit( get_template_directory() ) . 'inc/funnycoon-ajax-auth.php';

/**
 * Implement custom breadcrumbs
 */
require trailingslashit( get_template_directory() ) . 'inc/funnycoon-custom-breadcrumbs.php';
 
/**
 * Custom favicon for site. Favicons was generated by Favvy Favicon Exporter in Figma
*/
 
add_action( 'wp_head', 'add_favicon' );
add_action( 'admin_head', 'add_favicon' );

function add_favicon() {
    printf(
    '<link rel="icon" type="image/x-icon" href="' . get_template_directory_uri() . '/assets/favicon/favicon.ico">'
    );
}
 
 /**
  * 
  * Theme Setup
  * 
  */
 
 function funnycoon_setup() {
     add_theme_support('title-tag');
     add_theme_support( 'post-thumbnails' );
     register_nav_menus( array(
         'header_menu' => "Меню в header'e",
         'footer_menu' => "Меню в footer'e",
         'mobile_menu' => "Мобильное меню",
     ) );
 }
 add_action('after_setup_theme', 'funnycoon_setup');
 
 /**
  * 
  * Thumbnail custom setting (delete all sizes except thumbnail)
  * 
  */
 
 function devise_remove_default_image_sizes( $sizes) {
     unset( $sizes['thumbnail']);
     unset( $sizes['medium']);
     unset( $sizes['medium_large']);
     unset( $sizes['large']);
     unset( $sizes['768x432'] );
     unset( $sizes['1536x1536']); // disable 2x medium-large size
     unset( $sizes['2048x2048']); // disable 2x large size
     
     return $sizes;
 }
 add_filter('intermediate_image_sizes_advanced', 'devise_remove_default_image_sizes');

 /**
 *  Add post state to the project page (Edit profile page, Email edit page, Change password page)
 */

function ecs_add_post_state( $post_states, $post ) {

    if( $post->post_name == 'edit-profile' ) {
        $post_states[] = 'Profile edit page';
    }

    if( $post->post_name == 'change-email' ) {
        $post_states[] = 'Email edit page';
    }

    if( $post->post_name == 'change-password') {
        $post_states[] = 'Change password page';
    }

    return $post_states;
}

add_filter( 'display_post_states', 'ecs_add_post_state', 10, 2);

/**
 * Add notice to the profile edit page
 */

function ecs_add_post_notice() {

    global $post;

    if( isset( $post->post_name ) && ( ( $post->post_name == 'edit-profile' ) || ( $post->post_name == 'change-email' ) || ( $post->post_name == 'change-password' ) ) ) {

        // Add a notice to the edit page
        add_action( 'edit_form_after_title', 'ecs_add_page_notice', 1 );
            // Remove the WYSIWYG editor 
            remove_post_type_support('page', 'editor');
    }
}


function ecs_add_page_notice() {
    echo '<div class="notice notice-warning inline"><p>' . __( 'You are currently editing the profile edit page. Do not edit the title or slug of this page!', 'funnycoon' ) . '</p></div>';
}

add_filter( 'admin_notice', 'ecs_add_post_notice' );

/**
 * Check security (login user state) on edit profile page
 */

function check_page_security() {

    if ( !is_user_logged_in() ) {

        wp_redirect( home_url() );

        exit();

    }

}

/**
 * Custom login link in comments (when user not logged).
 * You can see it in the bottom of comment section
 */

function custom_comments_login_link( $defaults ) {
    $defaults['must_log_in'] = '<p class="must-log-in">Для отправки комментария вам необходимо <a href="#login" id="loginCommentBtn" class="popup-link">авторизоваться</a>.</p>';
    return $defaults;
}

add_filter( 'comment_form_defaults', 'custom_comments_login_link' );

/**
 * Custom login links in comment reply (when user not logged).
 * You can see it after every comment.
 */

function custom_comment_reply_login_link( $link ) {
    if( empty( $GLOBALS['user_ID'] ) && get_option( 'comment_registration' ) ) {

        return '<a rel="nofollow" class="comment-reply-login popup-link" href="#login" id="loginCommentReplyBtn">Войдите, чтобы ответить</a>';

    } else {

        return $link;

    }
}

add_filter( 'comment_reply_link', 'custom_comment_reply_login_link' );